version: "2.4"
networks:
  sispj_network:
    driver: bridge

services:
  microservices-db:
    image: postgres:12.1
    container_name: microservices-db
    environment:
       POSTGRES_DB: "microservices"
       POSTGRES_USER: "postgres"
       POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql   
